apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    name: clean-up
  name: clean-up
  annotations:
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: clean-up
  template:
    metadata:
      labels:
        app: clean-up
    spec:
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
        - name: docker-directory
          hostPath:
            path: /var/lib/docker
      containers:
        - image: r08041994b/containercleanup:latest
          name: clean-up
          env:
            - name: CLEAN_PERIOD
              value: "60"
            - name: DELAY_TIME
              value: "1800"
            - name: KEEP_IMAGES
              value: ""
            - name: KEEP_CONTAINERS
              value: ""
            - name: LOOP
              value: "true"
            - name: DEBUG
              value: "1"
            - name: DOCKER_API_VERSION
              value: "1.41"
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 128Mi
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: docker-sock
              readOnly: false
            - mountPath: /var/lib/docker
              name: docker-directory
              readOnly: false

